### ISSUE TITLE
Remove user

### ISSUE THREAD

**Issue by factor01211984** [UncleMeat/gazelle#3]
Hello I am Manish. When I am making test of website. I am add 30 user. Now I want to remove this but I can not see where is remove function is found. Is there any advice for this problem please?

**Comment by L4nz** [comment]
Gazelle do not have a remove user function. You can disable or ban a user from within the interface but you can not delete the account, this is intentional. You need to empty the database tables manually or reinstall the database.

**Comment by factor01211984** [comment]
Why is make this way? If I am remove user from database is remove?

**Comment by ValliusDax** [comment]
Well, you can remove the user profile entry from the user page if you have sufficient privilege (select delete from the dropdown near the bottom). But much of the data generated by this account will remain in the database, including, but not limited to: forum posts, torrent uploads, torrent comments and pms.

As removing the user account leaves a large amount of orphaned data it is highly recommended not to do this. If you are experimenting in a closed system then you have the luxury of being able to drop your database and import a fresh copy, this is the best solution for your specific issue.

**Comment by factor01211984** [comment]
Thank you very much for your kind advice. But what is the way tor reduce the user count? If is not by deleting the member?

**Comment by ValliusDax** [comment]
Why do you _need_ to reduce the user count, would it not be just as effective to disable those accounts and reduce the "enabled users" count?

As I said, if you must you can use the drop down to delete accounts, but not all information linked to the account is purged.

**Comment by factor01211984** [comment]
If you do not delete user account how can you keep accurate picture of user activity? If you are not properly delete user accounts you then is only have inflated statistic. 
Thank you again for advice. Where is option find to reduce enabled users count? Maybe this will help.

**Comment by ValliusDax** [comment]
Accurate count? Enabled users. You can also see the stats for users active in the last 24 hours/last week/last month.

To disable an account visit their profile page, select the dropdown which says enabled and change it to disabled and click save at the bottom.

**Comment by factor01211984** [comment]
I understand now. Thank you very much. :) You are most kind. Disable the user removes the user from the user count. Correct?

**Comment by ValliusDax** [comment]
yes

**Comment by factor01211984** [comment]
Thank you very much brother. You are most helpful.
